twig:
  file_name_pattern: "*.twig"
  paths:
    "%kernel.project_dir%/src/Dashboard/Infrastructure/Twig": dashboard
    "%kernel.project_dir%/src/Admin/Infrastructure/Twig": admin

when@test:
  twig:
    strict_variables: true
