executor: openchurch-app-hetzner
working_directory: ~/project
steps:
  - checkout:
      path: ~/project
  - run:
      name: Create .env.test.local
      command: |
        echo "DATABASE_URL=mysql://root:symfony@127.0.0.1:3306/openchurch?serverVersion=11.5.2-MariaDB&charset=utf8mb4" > .env.test.local
  - run:
      name: Install dependencies
      command: composer install --no-interaction --prefer-dist --no-progress --no-scripts

  # --- Security ---------------------------------------------------------------------------
  - run:
      name: Security check
      command: composer audit --abandoned=ignore

  # --- Static analysis --------------------------------------------------------------------
  - run:
      name: Run PHPStan
      command: composer phpstan
  - run:
      name: php-cs-fixer-check
      command: php vendor/bin/php-cs-fixer fix --dry-run --diff
  - run:
      name: rector (dry-run)
      command: vendor/bin/rector process --dry-run
  - run:
      name: composer validate
      command: composer validate --strict
  - run:
      name: "lint:container"
      command: php bin/console lint:container
  - run:
      name: "lint:yaml"
      command: php bin/console lint:yaml config src
  - run:
      name: "lint:twig"
      command: php bin/console lint:twig templates

  # --- Database schema --------------------------------------------------------------------
  - run:
      name: Install MySQL client
      command: apt-get update && apt-get install -y --no-install-recommends mariadb-client
  - run:
      name: Wait for mariadb to be stable...
      command: |
        count=0
        max_iterations=60
        until mariadb -h 127.0.0.1 -u root -psymfony -e "SELECT 1" > /dev/null 2>&1; do
            count=$((count + 1))
            if [ "$count" -ge "$max_iterations" ]; then
                echo "\nMax attempts reached. Exiting..."
                exit 1
            fi
            echo -n .
            sleep 5
        done
        echo "\nMariaDB is UP!"
  - run:
      name: Run migrations
      command: php bin/console doctrine:migrations:migrate --no-interaction
  - run:
      name: "doctrine:schema:validate"
      command: php bin/console doctrine:schema:validate -vvv
